"""Assemble the Markdown document for one article.

Two modes set upstream:
- "bilingual": English source → alternating EN/ZH paragraph pairs.
- "chinese_only": Chinese source (converted to Simplified) → Simplified
  Chinese only, no source-script text kept (owner's rule).
"""

import re
from datetime import date
from pathlib import Path

from src.agent.state import ArticleState
from src.agent.nodes.translator import FAILED_MARK

# One-line inline math span ($...$), not the block delimiter $$. The
# non-greedy body forbids $ and newlines, so $$...$$ blocks never match.
_INLINE_MATH_RE = re.compile(r"(?<!\$)(\$[^$\n]+?\$)(?!\$)")


def _pad_inline_math(text: str) -> str:
    """Ensure a space on both sides of inline math. Without it, a `$`
    glued to a CJK character is not recognised as a math delimiter by many
    Markdown note apps, which then mis-parse the surrounding text."""
    out: list[str] = []
    last = 0
    for m in _INLINE_MATH_RE.finditer(text):
        start, end = m.span()
        before = text[last:start]
        if before and not before[-1].isspace():
            before += " "
        out.append(before)
        out.append(m.group(1))
        if end < len(text) and not text[end].isspace():
            out.append(" ")
        last = end
    out.append(text[last:])
    return "".join(out)


def _bilingual_body(state: ArticleState, parts: list[str]) -> None:
    article = state["article"]
    if article["subtitle"]:
        parts.append(f"**{article['subtitle']}**")
        zh_subtitle = state.get("zh_subtitle", "")
        if zh_subtitle and zh_subtitle != FAILED_MARK:
            parts.append(f"**{zh_subtitle}**")
    for pair in state["translated_paragraphs"]:
        if pair.get("is_heading"):
            if pair["failed"] or pair["zh"].strip() == pair["en"].strip():
                parts.append(f"## {pair['en']}")
            else:
                parts.append(f"## {pair['zh']} | {pair['en']}")
            continue
        parts.append(pair["en"])
        if pair["failed"]:
            parts.append(f"{FAILED_MARK}\n\n{pair['en']}")
        elif pair["zh"].strip() != pair["en"].strip():
            # Untranslatable segments (author blocks, formulas) come back
            # verbatim — printing them twice helps nobody.
            parts.append(_pad_inline_math(pair["zh"]))


def _chinese_only_body(state: ArticleState, parts: list[str]) -> None:
    zh_subtitle = state.get("zh_subtitle", "")
    if zh_subtitle:
        parts.append(f"**{zh_subtitle}**")
    for pair in state["translated_paragraphs"]:
        parts.append(
            f"## {pair['zh']}" if pair.get("is_heading") else _pad_inline_math(pair["zh"])
        )


def formatter(state: ArticleState) -> dict:
    article = state["article"]
    mode = state.get("output_mode", "bilingual")
    zh_title = state.get("zh_title", "")
    parts: list[str] = []

    if mode == "chinese_only":
        parts.append(f"# {zh_title or article['title']}")
        note = "Converted to Simplified Chinese"
    else:
        heading = article["title"]
        if zh_title and zh_title != FAILED_MARK:
            heading = f"{zh_title} | {article['title']}"
        parts.append(f"# {heading}")
        note = "Machine translation — verify before quoting"

    parts.append(
        f"> Source: `{Path(state['pdf_path']).name}` · Style: {state['style']} · "
        f"Generated by pub2md-agent on {date.today().isoformat()} · {note}."
    )

    if mode == "chinese_only":
        _chinese_only_body(state, parts)
    else:
        _bilingual_body(state, parts)

    return {"bilingual_md": "\n\n".join(parts) + "\n"}
